---
title: "ReadMe for Data"
author: "The Nature Conservancy's LANDFIRE team"
date: "10/13/2021"
output: pdf_document
urlcolor: blue
---


This document serves to document changes made to datasets (will be repeated on website) and provide links to datasets.

## Goals and deliverables Phase 1
In general the aim of Phase 1 for ABRP is to get the data wrangled and to provide input that guides future monitoring, and eventually management.  

**Deliverables**

1. Cleaned datasets.  All datasets located in [this folder](https://tnc.box.com/s/dxuc1z646svvlkswcp3sp2ii75w8dk9l)
2. Charts of pine stems and wiregrass
3. LANDFIRE Maps and charts
4. Website with downloadable code

## Pine Data Wrangling
* worked from data delivered by Beatriz [ABRP_bioplots_1995-2018](https://tnc.box.com/s/elj2a00eq374a8vjho9i0hx0v6utdg12)
* added "B-P" column, concatenated BU and Plot numbers to generate unique value for charts
* added MONYEAR and LASTBURNYEAR columns for charts (also, some burns only had years recorded).  Used "text to columns" tool in Excel with "/" as the delimiter to create new YEAR-based columns where possible.  Manually entered years for many records.
* Bull-dozing happened (instead of fire?) for MONYEAR 2007, B-Ps 7_8, 7_7, 7_6, and 7_4.  Did not transfer this information to LASTBURNYEAR (but is is in LASTBURN column). Swaty did not want to mix numerical and text data types in the LASTBURNYEAR column.
* B-Ps 7_3, 7_5 was missing MONDATE information for 2019.  Swaty manually entered "2019" based on exploring neighboring plots in the dataset.
* Found many typos and case issues (e.g., "Seedling" instead of "SEEDLING")
* In pine.csv:
    * deleted 21_4 data for 2001
    * deleted 40_10 data for 1998
    
**Note-deletions only done in "pine.csv".  ABRP_bioplots_1995-2018 was left intact.**
    
## Pine Data 
There are multiple files with "pine" in the name.  Most were for charts.

1. [pine.csv](https://tnc.box.com/s/dpco8ijqnlibvda0wdyuwoaqmzcic8ga) **main pine dataset.**  Raw, but note processing steps above.  Some data deleted.  
2. for comparing stem counts to reference sites (BU 5)
    * [averagePineStemsBU](https://tnc.box.com/s/qtnq70ypf9nujsupb5bx3rbn1sfie6z5)
    * [pineBU5all](https://tnc.box.com/s/o1a5abi8pk2n1v04fprf1i36lkllil24)
    * [pineStemsBU5average](https://tnc.box.com/s/7mp042a9e3ogrhdnvy55h4px2o6abqxi) (intermediate dataset. Not used in charts.)
3. For heatmaps
    * [pineDiverge](https://tnc.box.com/s/oz95kdyg4a1yi84nz7ahqsfkp62con7g) (intermediate dataset. Not used in charts.)
    * [fiveStems](https://tnc.box.com/s/uuybgj4bnyj41vkmxeieyw7irw68ujhh) (intermediate dataset. Not used in charts.)
    * [comparePineClean](https://tnc.box.com/s/tthovx8jlvhrfzx8hofffb85hz5oko93) (intermediate dataset. Not used in charts.)

## Wiregrass data wrangling
In general worked with ABRP_bioplots_1995-2018 herb tab, then saved that to herb.WU.csv.  Wiregrass (perGrass.csv) data is a refinement of herb data. 

* All cleaned Herbaceous data saved as "herbWU.csv"
* For Perennial Grasses, that data was copied and pasted into a new spreadsheet, "perGrass.csv".   Used Pivot Table in herbWU.csv to create this new spreadsheet.  
* Assumed "99999" meant "no data". Changed to "NA".  Looks like (at least for some years) only one quadrat was sampled for % PG, % WP, % OP, % LI AND % BG.
* Did nothing with blank cells.
* Deleted rows with AVERAGES
* * Bull-dozing happened (instead of fire?) for MONYEAR 2007, B-Ps 7_8, 7_7, 7_6, and 7_4.  Did not transfer this information to LASTBURNYEAR (but is is in LASTBURN column). Swaty did not want to mix numerical and text data types in the LASTBURNYEAR column.
* In perGrass.csv:
    * deleted 21_4 data for 2001
    * deleted 40_10 data for 1998
    * recalculated average and standard dev for 2010, BP 7_1
    * fixed missing years for BP 7_1
    
## Wiregrass (perinnieal grass) datasets:

* [pergrass.csv](https://tnc.box.com/s/38aozohz7kchw9ezgs8mh402lke7e1yn) **main wiregrass dataset.**  Raw, but note processing steps above.  Some data deleted. 
* [herbWU.csv](https://tnc.box.com/s/ttwl42fiyh9ertv17txb9bq9d4o6wkqu) spreadsheet for working up the wiregrass data





