---
title: "to do"
author: "The Nature Conservancy's LANDFIRE team"
date: "7/6/2021"
output: html_document
---

FROM 10 Sept 21 meeting
* fix issue with BUP 7_1 which has several points for 2010 (appears to be an issue with the calculations in Excel?)
    * PINE raw data looks OK
    * PINE read in data (with mutate) looks OK
    * PINE seems OK
    * perGrass recalculated average and standard dev
    * perGrass fixed years with 7_1
* either add free axes OR print individual line charts for PINE (print to PDF?) DONE--PDF
* finish fixing heatmaps-DONE
* notes for 21_4 and 40_10...mystery data-Deleted for PINE;  Deleted for perGrass
* send cleaned up datasets

FROM 13 Sept
* perGrass 40_2 FIXED
* perGrass 40_5 FIXED
* points and lines do not match
* why are heat maps on the pine charts? FIXED
* with Grass charts is the box labeled wrong or in the wrong place? FIXED
* consider 3 size classes for pines
    * David and Chaz will get me numbers
    
with changes:
1. document on webpages
2. document on PDF
3. reknit
4. post to box

FROM Dec 2021:
1. Make new Seedlings page with (make sure class A is NOT with seedlings):
    * charts of 1995-2020 seedlings based on categories
    * charts of 2012-2020 seedlings raw counts
    * links to PDFs
2. Make sure that seedlings are NOT included in any pine charts on the main Pine page
3. Make sure all data is uploaded, and documented on data readme
4. Keep and review Grouped Pine charts


FROM Jan 2022:
1. Make seedlings only tab with:
    * showing entire time period by frequency class COMPLETE
    * showing 2012 to date by stem count COMPLETE
2. Class A tab
3. All other size classes (B and greater)  ASKED KRIS IF THIS IS GROUPED PINE OR PINE CHARTS (would need to pull something)(FEB 9) YES GROUPED PINE!






