---
title: "Pine stems per year by BU and size"
author: "The Nature Conservancy's LANDFIRE team"
date: "10/12/2021"
output: html_document
---


```{r pineChartsSetup, message=FALSE, warning=FALSE, include=FALSE}
pacman::p_load(tidyverse, ggsci, ggtext, readr, dplyr, DT, crosstalk, plotly, ggforce, slickR, ggplus, viridis)
theme_set(theme_bw())
```

# PINE

```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}

pine <- read_csv("data/pine.csv")
pine %>%
  mutate(MONYEAR = as.character(MONYEAR))
```





```{r echo=FALSE, message=FALSE, warning=FALSE, fig.height=8}


pdf("pineStemCharts.pdf")
pinePlotStems <-  
ggplot(pine, aes(MONYEAR, STEMS, color = SIZE, group = SIZE)) +
  geom_line(size=1.5, position = position_jitter(width = 0.0001, height = 1.0)) +
  geom_point() +
  theme_bw() +
  labs(
    title = "Pine stems per plot",
    subtitle = "Including size class",
    caption = "Data from TNC's Florida Chapter",
    x = "Monitoring Year",
    y = "Number of stems" ) +
  scale_color_simpsons()

facet_multiple(plot = pinePlotStems, 
               facets = 'BP', 
               ncol = 1, 
               nrow = 3,
               scales = "free")


```


# PINE GROUPED

```{r pineChartsSetup, message=FALSE, warning=FALSE, include=FALSE}
pacman::p_load(tidyverse, ggsci, ggtext, readr, dplyr, DT, crosstalk, plotly, ggforce, slickR, viridis, ggplus)
theme_set(theme_bw())

groupedPine <- read_csv("data/groupedPine.csv")
```


```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}
#make shared data for crosstalk
sdGroupedPine <- highlight_key(groupedPine)

```


```{r}
pdf("groupedPineStemCharts.pdf")

groupedPinePlotStems <-  
ggplot(sdGroupedPine, aes(MONYEAR, STEMS, color = GROUPS, group = GROUPS)) +
  geom_line(size=1.5, position = position_jitter(width = 0.0001, height = 1.0)) +
  geom_point() +
  theme_bw() +
  labs(
    title = "",
    caption = "Data from TNC's Florida Chapter",
    x = "Monitoring Year",
    y = "Number of stems",
       color = "Grouped Stem Size (in CM)") + 
  scale_color_viridis(discrete = TRUE, option = "D") +
  scale_fill_viridis(discrete = TRUE) 


facet_multiple(plot = groupedPinePlotStems, 
               facets = 'BP', 
               ncol = 1, 
               nrow = 3,
               scales = "free")

```



# WIREGRASS


```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}

perGrass <- read_csv("data/perGrass.csv")
perGrass %>%
  mutate(MONYEAR = as.character(MONYEAR))
```

```{r}
#devtools::install_github("guiastrennec/ggplus")
library(ggplus)

pdf("wiregrassCharts.pdf")

perGrassPlot <-  
ggplot(perGrass, aes(MONYEAR, meanPerPG, group = BP)) +
  geom_line(size=1.5, position = position_jitter(width = 0.0001, height = 1.0)) +
  geom_point() +
  theme_bw() +
  labs(
    title = "Average Percent Perinnial Grass per plot",
    caption = "Data from TNC's Florida Chapter",
    x = "Monitoring Year",
    y = "Mean Percent" ) +
  scale_color_simpsons()

facet_multiple(plot = perGrassPlot, 
               facets = 'BP', 
               ncol = 1, 
               nrow = 3,
               scales = "free")


```



## Pine Seedlings Coded

```{r}
seedlings <- read_csv("data/pineSeedlingsOnly.csv")
seedlings %>%
  mutate(MONYEAR = as.character(MONYEAR)) 
```


```{r}

#devtools::install_github("guiastrennec/ggplus")
library(ggplus)

pdf("PineSeedlingsCats.pdf")


pineSeedlingsCats <-  
ggplot(seedlings, aes(MONYEAR, STEMS)) +
  geom_line(aes(group = 1), size = 0.5, color = '#54524d') +
  geom_point() +
  theme_bw() +
  labs(
    title = "Pine seedlings per plot",
    subtitle = "cODED (1 = 1-5 seedlings; 2 = 6-20 seedlings; 3 > 20 seedlings ",
    caption = "Data from TNC's Florida Chapter",
    x = "Year",
    y = "Stem count category" ) 

facet_multiple(plot = pineSeedlingsCats, 
               facets = 'BP', 
               ncol = 1, 
               nrow = 3,
               scales = "free")
```


## Pine Seedlings RAW

```{r}
seedlings <- read_csv("data/pineSeedlingsOnly.csv")
seedlings %>%
  mutate(MONYEAR = as.character(MONYEAR)) 


seedlings2012 <- seedlings %>%
  filter(MONYEAR > 2011)

```


```{r}

#devtools::install_github("guiastrennec/ggplus")
library(ggplus)

pdf("PineSeedlingsRAW.pdf")


pineSeedlingsRaw <-  
ggplot(seedlings, aes(MONYEAR, STEMSraw)) +
  geom_line(aes(group = 1), size = 0.5, color = '#54524d') +
  geom_point() +
  theme_bw() +
  labs(
    title = "Pine seedlings per plot",
    subtitle = "Raw counts, 2012-2020",
    caption = "Data from TNC's Florida Chapter",
    x = "Year",
    y = "Stem count" ) 

facet_multiple(plot = pineSeedlingsRaw, 
               facets = 'BP', 
               ncol = 1, 
               nrow = 3,
               scales = "free")
```

## Make pine charts without seedlings


```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}

pine <- read_csv("data/pineALL.csv")
pine %>%
  mutate(MONYEAR = as.character(MONYEAR))

#remove seedlings from base dataset
pineWOseedlings <- pine %>%
      filter(`SIZE(noCM)` != "SEEDLING")
```

```{r}
library(ggplus)

pdf("pineWOseedlingsPlotStems.pdf")


pineWOseedlingsPlotStems <-  
ggplot(pineWOseedlings, aes(MONYEAR, STEMS, color = SIZE, group = BP)) +
  geom_line(size=1.5, position = position_jitter(width = 0.0001, height = 1.0)) +
  geom_point() +
  theme_bw() +
  labs(
    title = "Pine stems per plot",
    subtitle = "Including size class",
    caption = "Data from TNC's Florida Chapter",
    x = "Monitoring Year",
    y = "Number of stems" ) +
  scale_color_simpsons()

facet_multiple(plot = pineWOseedlingsPlotStems, 
               facets = 'BP', 
               ncol = 1, 
               nrow = 3,
               scales = "free")


```


# GROUPED PINE

```{r pineChartsSetup, message=FALSE, warning=FALSE, include=FALSE}
pacman::p_load(tidyverse, ggsci, ggtext, readr, dplyr, DT, crosstalk, plotly, ggforce, slickR, viridis)


groupedPine <- read_csv("data/pineAll.csv")%>%
      filter(`SIZE(noCM)` != "SEEDLING")
                
```

```{r}
library(ggplus)

pdf("groupedPineStems.pdf")

groupedPinePlotStems <-  
ggplot(sdSumsGroupedPine, aes(MONYEAR, sumSTEMS, color = GROUPS, group = GROUPS)) +
  geom_line(size=1.5, position = position_jitter(width = 0.0001, height = 1.0)) +
  geom_point() +
  theme_bw() +
  labs(
    title = "",
    caption = "Data from TNC's Florida Chapter",
    x = "Monitoring Year",
    y = "Number of stems",
    color = "Grouped Stem Size (in CM)") + 
  scale_color_viridis(discrete = TRUE, option = "D")

facet_multiple(plot = groupedPinePlotStems, 
               facets = 'BP', 
               ncol = 1, 
               nrow = 3,
               scales = "free")

```


## Class A Pine

```{r}
classA <- read_csv("data/pineClassAonly.csv") %>%
  mutate(MONYEAR = as.character(MONYEAR)) 
```


```{r}

library(ggplus)

pdf("classAstems.pdf")

pineClassA <-  
ggplot(classA , aes(MONYEAR, STEMS)) +
  geom_line(aes(group = 1), size = 0.5, color = '#54524d') +
  geom_point() +
  labs(
    title = "Pine class A per BU-Plot",
    subtitle = "Only Class Adev",
    caption = "Data from TNC's Florida Chapter",
    x = "Year",
    y = "Stem count code" ) 




facet_multiple(plot = pineClassA, 
               facets = 'BP', 
               ncol = 1, 
               nrow = 3,
               scales = "free")

```

