---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Contains the cleaned long-term monitoring datasets, basic exploratory charts, LANDFIRE maps and documentation for the [Apalachicola Bluffs and Ravines Preserve](https://www.nature.org/en-us/get-involved/how-to-help/places-we-protect/apalachicola-bluffs-and-ravines-preserve/).  

## Goals
The overall goal of this project was to organize and explore the long-term monitoring data so that the Florida chapter could:

* assess future monitoring needs
* explore effectiveness of treatments
* be set up for efficient future data recording

Plus have LANDFIRE data-based maps for landscape context.

## Deliverables include:

* cleaned datasets (download this [document](https://github.com/rswaty/ABRPweb/raw/master/dataDoc.pdf) for links to data)
* charts of
    * pine stem counts over time by size class, separate chart per Burn Unit-Plot.  See all charts on Pine Charts page.
    * wiregrass percent cover over time, separate chart per Burn Unit-Plot. See all charts on Perennial Grass Charts page. 
* LANDFIRE maps
* *this website* mostly created as a sandbox and for learning/teaching by the developer.  Also serves as additional documentation and contains code for data processing and charts.  Click "Source Code" button to get all datasets and code. 

## People who contributed to current work

* Beatiz Pace-Aldana
* Chaz Oliver
* David Printiss
* Kris Serbesoff-King
* Laura Roncal
* Randy Swaty

## People who contributed to data collection (from datasheets; may not be inclusive)

* Doria and other person who did previous analysis (link to)



